name: hello-world
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: step1
	run: echo "Hello , moto!"
  job2: 
    runs-on: ubuntu-latest
    steps: 
      - name: step2
	run: echo "Hello world 2"
		
