name: hello-world
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step2
        run: echo "Hwllo. skdfhsdkjhfs"
      - name: step4
        run: echo "ksfksjjfksjfs"
	  - name: step5
	    run: echo "${{ secrets.GITHUB_TOKEN }}"
